#!/usr/bin/env bash
# A `stat` PATH shim that reproduces real GNU coreutils behavior for the
# `-f %m` / `-f%m` / `-c %Y` / `-c%Y` invocation shapes used by the
# cross-platform mtime idiom in scripts/PORTABILITY.md #1.
#
# WHY THIS EXISTS
#
# The portability bug this suite guards against only shows up under GNU
# coreutils (Linux). Every contributor and CI's own macOS-less runner still
# needs to catch a regression WITHOUT a Linux box or Docker handy. This shim
# makes any host behave exactly like measured GNU coreutils 9.4
# (ubuntu:24.04) for these four shapes, so the real target script can be run
# unmodified and exercise the Linux code path deterministically everywhere.
#
# MEASURED 2026-09-25 (docker run --rm ubuntu:24.04 ...; see docs/PORTABILITY.md
# and the PR that added this file for the transcript):
#
#   stat -c %Y FILE   -> epoch mtime on stdout, rc=0   (correct GNU form)
#   stat -c%Y FILE    -> epoch mtime on stdout, rc=0   (glued short option, same)
#   stat -f %m FILE   -> multi-line NON-NUMERIC filesystem-status text on
#                        stdout, rc=1. GNU's `-f` means --file-system; `%m` is
#                        not a recognized filesystem-mode directive, and BOTH
#                        "%m" and FILE get statted as filesystem targets, so
#                        the "%m" lookup fails (rc=1) while FILE's filesystem
#                        info still prints to stdout before that failure.
#   stat -f%m FILE    -> "stat: invalid option -- '%'" on stderr, rc=1, EMPTY
#                        stdout (glued form fails at option-parsing, before
#                        touching any operand -- no garbage leaks to stdout).
#
# Only these four shapes are implemented. This is a narrow test double for
# the mtime idiom, not a stat reimplementation -- anything else is a hard
# error so a test relying on unimplemented behavior fails loudly instead of
# reading a wrong answer as a real one.
#
# USAGE
#   . "$(dirname "${BASH_SOURCE[0]}")/lib/gnu_stat_shim.sh"
#   SHIMDIR="$TMP/gnu-stat-shim"
#   install_gnu_stat_shim "$SHIMDIR"
#   PATH="$SHIMDIR:$PATH" bash "$SCRIPT_UNDER_TEST" ...

# install_gnu_stat_shim DIR -- writes an executable `stat` into DIR (created
# if needed). Caller is responsible for putting DIR on PATH ahead of the
# real stat.
install_gnu_stat_shim() {
  local dir="${1:-}"
  if [ -z "$dir" ]; then
    echo "install_gnu_stat_shim: a directory argument is required" >&2
    return 2
  fi
  mkdir -p "$dir"
  cat > "$dir/stat" <<'SHIM'
#!/usr/bin/env bash
# Generated by tests/integration/lib/gnu_stat_shim.sh -- see that file for the
# measured GNU behavior this reproduces. Do not edit in place.
set -eu

_real_mtime() {
  # Portable epoch mtime of $1, independent of which `stat` is really
  # installed on this host (the whole point: this must give the same answer
  # on macOS and Linux alike, since it stands in for GNU on BOTH).
  python3 -c 'import os, sys; print(int(os.path.getmtime(sys.argv[1])))' "$1"
}

case "${1:-}/${2:-}" in
  "-c/%Y")
    _real_mtime "$3"
    exit 0
    ;;
  "-f/%m")
    printf '  File: "%s"\n    ID: 0000000000000000 Namelen: 255     Type: overlayfs\nBlock size: 4096       Fundamental block size: 4096\n' "$3"
    echo "stat: cannot read file system information for '$2': No such file or directory" >&2
    exit 1
    ;;
  *)
    case "${1:-}" in
      -c%Y)
        _real_mtime "$2"
        exit 0
        ;;
      -f%m)
        echo "stat: invalid option -- '%'" >&2
        exit 1
        ;;
    esac
    echo "gnu_stat_shim: unsupported invocation: stat $*" >&2
    exit 2
    ;;
esac
SHIM
  chmod +x "$dir/stat"
}
