#!/usr/bin/env python3
"""
aggregate-sessions.py — rebuild Last Session.md from {VAULT}/⚙️ Meta/Sessions/*.md

Problem: multiple Claude Code worktrees running session-end cascades
concurrently raced on Last Session.md writes. Last write wins. Entries from
earlier sessions were silently clobbered.

Fix: each session writes its content to its own unique file in
{VAULT}/⚙️ Meta/Sessions/ (filename: YYYY-MM-DDTHH-MM-{worktree}.md). This
script rebuilds Last Session.md by concatenating the N most recent session
files in reverse chronological order. Because the output is a deterministic
function of the sorted input, concurrent runs of this script produce
identical output — safe against races.

Usage:
  VAULT_ROOT=/path/to/vault python3 aggregate-sessions.py
  python3 aggregate-sessions.py --keep 5
  python3 aggregate-sessions.py --dry-run
  python3 aggregate-sessions.py --no-legacy

Environment variables:
  VAULT_ROOT   — absolute path to the Obsidian vault root.
                 Defaults to $HOME/Documents/MyVault — CUSTOMIZE THIS or
                 set the env var in your shell / hook.

File format (Sessions/ entries):
  Each file must start with YAML frontmatter containing:
    - creationDate (ISO 8601)
    - type: session
    - worktree: {name}   (or "main" for non-worktree sessions)
    - session_date: YYYY-MM-DD
    - session_label: "..."  (use "update pending" for stubs to filter)
  Body starts with a "# Session — ..." top-level heading.

Stub filtering: files with `session_label: "update pending"` are excluded
from the aggregated view so orphaned placeholders don't pollute
Last Session.md. A stub becomes a real entry once Claude fills in its body
and changes the session_label.

Determinism rules:
  - Files sorted by filename descending (reverse ISO timestamp order)
  - Top N concatenated with "---" separators
  - Deterministic preamble + aggregator region markers
  - Same input → same output, always → concurrent runs are safe

Safety:
  - If Sessions/ is empty, this script DOES NOT touch Last Session.md.
    This prevents wiping a historical file on first run before migration.
  - Pre-split historical content is preserved below the aggregator region
    under a "## Legacy (pre-split) historical entries" header.
  - Pass --no-legacy to disable legacy preservation (destructive — review
    before using on a vault with existing content).
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
from pathlib import Path

# VAULT_ROOT — override via env var, or edit this default for your setup.
VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", os.path.expanduser("~/Documents/MyVault")))
META_DIR = VAULT_ROOT / "⚙️ Meta"
SESSIONS_DIR = META_DIR / "Sessions"
LAST_SESSION = META_DIR / "Last Session.md"

AGGREGATOR_BEGIN = "<!-- aggregate-sessions:BEGIN -->"
AGGREGATOR_END = "<!-- aggregate-sessions:END -->"
LEGACY_HEADER = "## Legacy (pre-split) historical entries"


def preamble() -> str:
    return (
        "---\n"
        f"creationDate: {dt.date.today().isoformat()}\n"
        "type: meta\n"
        "---\n"
        "\n"
        "*Auto-generated by `⚙️ Meta/scripts/aggregate-sessions.py` from "
        "`⚙️ Meta/Sessions/`. Do not edit this file directly — edit the "
        "individual session files instead and re-run the aggregator (or "
        "wait for the next session-end hook to run it). Historical entries "
        "that were written before the per-worktree split live below the "
        "aggregator region as legacy content.*\n"
        "\n"
    )


def is_stub(content: str) -> bool:
    """A stub is a session file written by the session-end hook but not
    yet filled in by Claude. Detect via the `session_label: "update
    pending"` line in the frontmatter OR the placeholder marker in the
    body. Stubs are excluded from the aggregator view."""
    if 'session_label: "update pending"' in content:
        return True
    if "stub written by session-end-hook.sh" in content:
        return True
    return False


def gather_session_files(include_stubs: bool = False) -> list[Path]:
    """Return session files sorted by filename descending (newest first).

    By default, stub files are excluded. Pass include_stubs=True to
    include them."""
    if not SESSIONS_DIR.exists():
        return []
    all_files = [p for p in SESSIONS_DIR.glob("*.md") if p.is_file()]
    if not include_stubs:
        all_files = [
            p for p in all_files if not is_stub(p.read_text(encoding="utf-8"))
        ]
    return sorted(all_files, key=lambda p: p.name, reverse=True)


def strip_frontmatter(content: str) -> str:
    """Remove the YAML frontmatter block at the top of a session file."""
    if content.startswith("---\n"):
        end = content.find("\n---\n", 4)
        if end != -1:
            return content[end + 5 :].lstrip("\n")
    return content


def truncate_body(body: str, max_lines: int, source_file: Path) -> str:
    """Truncate a session body to max_lines, adding a pointer to the full file."""
    lines = body.split("\n")
    if max_lines <= 0 or len(lines) <= max_lines:
        return body
    truncated = "\n".join(lines[:max_lines])
    truncated += (
        f"\n\n> *[truncated — {len(lines)} lines total. "
        f"Full session: `⚙️ Meta/Sessions/{source_file.name}`]*"
    )
    return truncated


def build_aggregate(files: list[Path], keep: int, max_lines: int = 0) -> str:
    """Build the aggregator region content from the top N session files."""
    top = files[:keep]
    blocks = []
    for f in top:
        body = strip_frontmatter(f.read_text(encoding="utf-8")).rstrip()
        if max_lines > 0:
            body = truncate_body(body, max_lines, f)
        blocks.append(body)

    header = (
        f"{AGGREGATOR_BEGIN}\n"
        f"*Last aggregated: {dt.datetime.now().strftime('%Y-%m-%d %H:%M')} — "
        f"showing top {len(top)} of {len(files)} session(s) from "
        f"`⚙️ Meta/Sessions/`.*\n"
        "\n"
        "> **Rotated sessions:** older entries beyond the top N still live "
        "in `⚙️ Meta/Sessions/` — read those when you need historical "
        "context.\n"
        "\n"
        "---\n\n"
    )
    body = "\n\n---\n\n".join(blocks)
    footer = f"\n\n{AGGREGATOR_END}\n"
    return header + body + footer


def extract_legacy(existing: str) -> str:
    """Return the legacy (pre-split) historical content from an existing
    Last Session.md, for preservation across aggregator runs.

    Steady-state: legacy header present → return content below it.
    First run: no legacy header → treat everything below the frontmatter
    as legacy."""
    legacy_idx = existing.find(LEGACY_HEADER)
    if legacy_idx != -1:
        # Strip the header itself — main() re-adds it.
        after_header = existing[legacy_idx + len(LEGACY_HEADER) :].lstrip("\n")
        return after_header.rstrip()

    # First-run migration: no legacy header yet.
    if existing.startswith("---\n"):
        fm_end = existing.find("\n---\n", 4)
        if fm_end != -1:
            below_fm = existing[fm_end + 5 :].lstrip("\n")
            # Strip any leftover aggregator region from a buggy earlier run
            if AGGREGATOR_BEGIN in below_fm:
                pattern = re.compile(
                    re.escape(AGGREGATOR_BEGIN)
                    + r".*?"
                    + re.escape(AGGREGATOR_END),
                    re.DOTALL,
                )
                below_fm = pattern.sub("", below_fm)
            # Strip an "*Auto-generated...*" preamble line if present
            below_fm = re.sub(
                r"^\*Auto-generated[^\n]*\*\s*\n+",
                "",
                below_fm,
                count=1,
                flags=re.MULTILINE,
            )
            return below_fm.strip()
    return existing.rstrip()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild Last Session.md from ⚙️ Meta/Sessions/*.md"
    )
    parser.add_argument(
        "--keep", type=int, default=2, help="Number of sessions to show (default: 2)"
    )
    parser.add_argument(
        "--max-lines",
        type=int,
        default=60,
        help="Max lines per session entry before truncation (default: 60)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview without writing"
    )
    parser.add_argument(
        "--no-legacy",
        action="store_true",
        help="Don't preserve historical content below the aggregator region",
    )
    args = parser.parse_args()

    if not META_DIR.exists():
        print(
            f"ERROR: {META_DIR} does not exist. Set VAULT_ROOT env var "
            f"to your vault path.",
            file=sys.stderr,
        )
        return 1

    files = gather_session_files()

    if not files:
        print(
            f"WARNING: {SESSIONS_DIR} is empty. Not touching {LAST_SESSION.name}.",
            file=sys.stderr,
        )
        return 0

    aggregate_block = build_aggregate(files, args.keep, args.max_lines)

    if LAST_SESSION.exists() and not args.no_legacy:
        existing = LAST_SESSION.read_text(encoding="utf-8")
        legacy = extract_legacy(existing)
    else:
        legacy = ""

    new_content = preamble() + aggregate_block
    if legacy:
        new_content += f"\n\n---\n\n{LEGACY_HEADER}\n\n"
        new_content += legacy.rstrip() + "\n"

    if args.dry_run:
        print(f"--- DRY RUN ---")
        print(f"Would write {len(new_content):,} bytes to {LAST_SESSION.name}")
        print(f"Top {min(args.keep, len(files))} of {len(files)} session(s):")
        for f in files[: args.keep]:
            print(f"  - {f.name}")
        return 0

    LAST_SESSION.write_text(new_content, encoding="utf-8")
    print(
        f"Aggregated {min(args.keep, len(files))} of {len(files)} session(s) "
        f"into {LAST_SESSION.name} ({len(new_content):,} bytes)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
