#!/usr/bin/env python3
"""
aggregate-decisions.py — rebuild Decision Log.md from {VAULT}/⚙️ Meta/Decisions/*.md

Sister script to aggregate-sessions.py. Same rationale: concurrent
worktrees racing on Decision Log.md writes silently clobbered entries.
Fix: each decision lives in its own file in Decisions/, this script
rebuilds Decision Log.md by concatenating all decision files in reverse
chronological order.

Difference from sessions: decisions are small and permanent — this
script shows ALL of them in Decision Log.md, not just the top N. If the
log gets unwieldy, rotation is a separate future concern.

Usage:
  VAULT_ROOT=/path/to/vault python3 aggregate-decisions.py
  python3 aggregate-decisions.py --dry-run
  python3 aggregate-decisions.py --no-legacy

Environment variables:
  VAULT_ROOT   — absolute path to the Obsidian vault root.
                 Defaults to $HOME/Documents/MyVault — CUSTOMIZE or set env var.

File format (Decisions/ entries):
  Each file must start with YAML frontmatter containing:
    - creationDate (ISO 8601)
    - type: decision
    - worktree: {name}  (or "main")
    - decision_date: YYYY-MM-DD
    - floor: {emotional floor at decision time}
    - stakes: Low | Medium | High
    - speed: Instant | Hours | Days | Weeks
    - outcome: pending | {fill-in-later}
    - pattern: pending | {fill-in-later}
  Body is the decision entry (What / Why / Floor / Stakes / Speed / ...).

Determinism rules identical to aggregate-sessions.py: sorted filename
descending → deterministic output → concurrent runs safe.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
from pathlib import Path

# Auto-detect from script location (⚙️ Meta/scripts/ → 2 levels up), or override via env var.
_SCRIPT_DIR = Path(__file__).resolve().parent
VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", str(_SCRIPT_DIR.parent.parent)))
META_DIR = VAULT_ROOT / "⚙️ Meta"
DECISIONS_DIR = META_DIR / "Decisions"
DECISION_LOG = META_DIR / "Decision Log.md"

AGGREGATOR_BEGIN = "<!-- aggregate-decisions:BEGIN -->"
AGGREGATOR_END = "<!-- aggregate-decisions:END -->"
LEGACY_HEADER = "## Legacy (pre-split) historical decisions"


def preamble() -> str:
    return (
        "---\n"
        f"creationDate: {dt.date.today().isoformat()}\n"
        "type: meta\n"
        f"last_updated: {dt.date.today().isoformat()}\n"
        "---\n"
        "\n"
        "# Decision Log\n"
        "\n"
        "*Tracking decisions to learn patterns over time. What I chose, why, "
        "what I was feeling, and what happened.*\n"
        "\n"
        "**Auto-generated** by `⚙️ Meta/scripts/aggregate-decisions.py` from "
        "`⚙️ Meta/Decisions/`. Do not edit this file directly — create or "
        "edit individual decision files in `⚙️ Meta/Decisions/` and re-run "
        "the aggregator (or let the session-end hook run it). Pre-split "
        "historical decisions are preserved as legacy content below the "
        "aggregator region.*\n"
        "\n"
        "## What to Track Per Decision\n"
        "\n"
        "- **What:** The decision in one sentence\n"
        "- **Why:** The reasoning — what tipped it\n"
        "- **Floor:** What emotional floor I was on when I decided\n"
        "- **Stakes:** Low / Medium / High\n"
        "- **Speed:** Instant / Hours / Days / Weeks\n"
        "- **Outcome:** (fill in later) What actually happened\n"
        "- **Pattern:** (fill in later) What this reveals about how I decide\n"
        "\n"
        "---\n"
        "\n"
    )


def gather_decision_files() -> list[Path]:
    """Return decision files sorted by filename descending (newest first)."""
    if not DECISIONS_DIR.exists():
        return []
    return sorted(
        [p for p in DECISIONS_DIR.glob("*.md") if p.is_file()],
        key=lambda p: p.name,
        reverse=True,
    )


def strip_frontmatter(content: str) -> str:
    if content.startswith("---\n"):
        end = content.find("\n---\n", 4)
        if end != -1:
            return content[end + 5 :].lstrip("\n")
    return content


def build_aggregate(files: list[Path]) -> str:
    blocks = []
    for f in files:
        body = strip_frontmatter(f.read_text(encoding="utf-8")).rstrip()
        blocks.append(body)

    header = (
        f"{AGGREGATOR_BEGIN}\n"
        f"*Last aggregated: {dt.datetime.now().strftime('%Y-%m-%d %H:%M')} — "
        f"{len(files)} decision(s) from `⚙️ Meta/Decisions/`, newest first.*\n"
        "\n"
    )
    body = "\n\n---\n\n".join(blocks)
    footer = f"\n\n{AGGREGATOR_END}\n"
    return header + body + footer


def extract_legacy(existing: str) -> str:
    """Preserve pre-split historical decisions across aggregator runs.

    Steady-state: legacy header present → return content below it.
    First run: no legacy header → find the first '## YYYY-' heading
    (hand-written section markers like '## 2026-04') and preserve from
    there down."""
    legacy_idx = existing.find(LEGACY_HEADER)
    if legacy_idx != -1:
        after_header = existing[legacy_idx + len(LEGACY_HEADER) :].lstrip("\n")
        return after_header.rstrip()

    match = re.search(r"^## \d{4}-", existing, re.MULTILINE)
    if match:
        return existing[match.start() :].rstrip()
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild Decision Log.md from ⚙️ Meta/Decisions/*.md"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview without writing"
    )
    parser.add_argument(
        "--no-legacy",
        action="store_true",
        help="Don't preserve historical content below the aggregator region",
    )
    args = parser.parse_args()

    if not META_DIR.exists():
        print(
            f"ERROR: {META_DIR} does not exist. Set VAULT_ROOT env var "
            f"to your vault path.",
            file=sys.stderr,
        )
        return 1

    files = gather_decision_files()

    if not files:
        print(
            f"WARNING: {DECISIONS_DIR} is empty. Not touching {DECISION_LOG.name}.",
            file=sys.stderr,
        )
        return 0

    aggregate_block = build_aggregate(files)

    if DECISION_LOG.exists() and not args.no_legacy:
        existing = DECISION_LOG.read_text(encoding="utf-8")
        legacy = extract_legacy(existing)
    else:
        legacy = ""

    new_content = preamble() + aggregate_block
    if legacy:
        new_content += f"\n\n---\n\n{LEGACY_HEADER}\n\n"
        new_content += legacy.rstrip() + "\n"

    if args.dry_run:
        print(f"--- DRY RUN ---")
        print(f"Would write {len(new_content):,} bytes to {DECISION_LOG.name}")
        print(f"{len(files)} decision(s):")
        for f in files:
            print(f"  - {f.name}")
        return 0

    DECISION_LOG.write_text(new_content, encoding="utf-8")
    print(
        f"Aggregated {len(files)} decision(s) into {DECISION_LOG.name} "
        f"({len(new_content):,} bytes)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
