#!/usr/bin/env python3
"""dev-build-reclaim — reclaim regenerable BUILD ARTIFACTS from idle worktrees.

THE GAP THIS CLOSES: the per-session worktree pattern creates a full checkout per
ticket, and each one grows its own compiled output. Every other reclaim leg in the
daily pass frees build output only as a SIDE EFFECT of deleting a whole worktree:

  * worktree-prune.sh / dev-worktree-prune.py — remove ORPHANED worktrees.
  * dev-repo-reaper.py — git objects only, and reaps a worktree ONLY when its
    branch is provably merged.

So a worktree that legitimately STAYS (unmerged, in-flight, long-lived) keeps its
multi-GB `target/` forever — and that is the majority case. Measured 2026-08-05 on
a maintainer machine: ~130 worktrees held 438 GB of build output (64 Rust `target/`
= 346 GB, 124 `node_modules` = 77 GB) while every GC leg ran green daily and the
926 GB volume fell to 2.3 GB free.

Sibling of dev-repo-reaper.py, deliberately NOT a tier inside it: the decision
input is different (filesystem mtime, not git merge-state) and the two must run
independently — artifacts are reclaimable from a worktree whose BRANCH must stay.

RECLAIMS (all regenerated by a build command, never source, never git metadata):
  node_modules   -> pnpm/npm install
  .venv          -> uv sync / python -m venv
  .next .turbo   -> next build
  target/        -> cargo build   (ONLY when a sibling Cargo.toml proves it is
                                   Rust build output, so a source dir merely
                                   NAMED "target" is never touched)

NEVER TOUCHED: any other directory, any file, .git, a worktree with a LIVE session
lock, and any worktree whose SOURCE was modified within the active idle threshold —
in-flight work keeps its build cache so the next session pays no full rebuild.

Generic `dist`/`build` names are EXCLUDED by design: ambiguous (frequently
checked-in source), and measured at only ~0.4 GB of the 490 GB.

DRY-RUN BY DEFAULT. --apply deletes and appends a JSON manifest to
<log-dir>/build-reclaim-<date>.jsonl (what, how big, how idle) so a reclaim is
always auditable after the fact.

--- Three defects this carries fixes for (found 2026-08-05, after the disk hit
    2.3 GB free while the tool ran green)

[1] IDLE SIGNAL WAS CONTAMINATED BY THE BUILD ITSELF. The idle probe read the
    worktree ROOT dir. A directory's mtime bumps when an entry is added or removed
    inside it — including `target/`. So compiling, the act that CREATES the
    multi-GB artifact, reset the clock deciding whether to reclaim it: the
    abandonment signal was a function of the activity it was measuring. Worktrees
    dormant 9d read as 0.0d idle. Now: newest mtime over SOURCE entries only
    (skips .git and every artifact dir, and never the root itself).

[2] A FIXED THRESHOLD CANNOT OUTRUN UNBOUNDED WORKTREE CREATION. Pinned at 7 days
    it reclaimed ~15 GB/day against faster growth; at 17 GB free it reclaimed
    1.3 GB and reported success. Now the threshold TIGHTENS as free space falls
    (PRESSURE_LADDER), bottoming at 0d — reclaim everything not session-locked —
    so the floor is defended regardless of creation rate.

[3] SYMLINKED ARTIFACTS CRASHED THE DELETE. rmtree refuses a symlink, so a
    symlinked `node_modules` failed every run and its space was never reclaimed.
    Now unlinked, and sized as 0 (the link is never followed out of the worktree).

Artifacts are deleted LARGEST-FIRST, so a pressure-triggered run buys back the
most space in its first seconds rather than its last.

Usage:
  dev-build-reclaim.py                      # dry-run over the whole dev root
  dev-build-reclaim.py --apply              # execute
  dev-build-reclaim.py --min-idle-days 14   # pin the threshold (skips the ladder)
  dev-build-reclaim.py --min-free-gb 200    # no-op unless free space is below this
  dev-build-reclaim.py --dev-root /path     # override the dev root for this run
  dev-build-reclaim.py --json               # machine-readable plan

Config: the dev root resolves from $ABS_DEV_ROOT, else the install config's
`dev_root`, else ~/dev — so this is never hardcoded to one machine's layout.
Log dir override: $DEV_BUILD_RECLAIM_LOG_DIR (tests point this at a temp dir so a
run never writes a manifest into the operator's real audit trail).
"""
# exit-contract: NOT-A-CHECKER -- deletes regenerable build artifacts from
#   worktrees


from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


def _add_lib_to_path() -> bool:
    candidates = [
        os.environ.get("DEV_REPO_SCAN_DIR"),
        # This script's own sibling first: a ~/.claude/hooks copy can be an older
        # deploy, and a stale resolver here decides what gets DELETED.
        str(Path(__file__).resolve().parent.parent / "hooks"),
        str(Path.home() / ".claude" / "skills" / "ai-brain-starter" / "hooks"),
        str(Path.home() / ".claude" / "hooks"),
    ]
    for c in candidates:
        if c and (Path(c) / "_lib" / "dev_repo_scan.py").exists():
            sys.path.insert(0, c)
            return True
    return False


if not _add_lib_to_path():
    print("dev-build-reclaim: could not locate _lib/dev_repo_scan.py "
          "(set DEV_REPO_SCAN_DIR).", file=sys.stderr)
    sys.exit(2)

try:
    from _lib.dev_repo_scan import (  # noqa: E402
        has_live_session_lock,
        resolve_dev_root,
    )
except ImportError as exc:
    print(f"dev-build-reclaim: the _lib/dev_repo_scan.py on sys.path is older "
          f"than this script ({exc}). Re-run scripts/install-hooks-user-level.py. "
          f"Refusing to delete anything on a resolver I cannot trust.",
          file=sys.stderr)
    sys.exit(2)

# Fail-CLOSED process-liveness gate, resolved defensively so an older deployed
# _lib makes this tool REFUSE deletions rather than fail to import and quietly
# revert to the unguarded path.
try:
    from _lib.worktree_safety import process_busy_reason as _process_busy_reason
except Exception:  # pragma: no cover - depends on the deployed layout
    _process_busy_reason = None  # type: ignore[assignment]


def worktree_busy(wt: Path, cache: dict | None = None) -> str | None:
    """Why `wt`'s build output must not be reclaimed, or None.

    Probes the WORKTREE, never the artifact directory: a compiler does not sit
    in `target/`, it sits in the source root and writes into it. Probing the
    artifact dir would answer "nobody home" for exactly the build this exists to
    protect. An absent or broken probe REFUSES — the bottom pressure rung sets
    the idle threshold to zero days, which every worktree passes, so this gate
    and the session lock are all that stand between an actively-compiling tree
    and losing its cache.
    """
    if _process_busy_reason is None:
        return ("process-liveness helper unavailable in this _lib deploy; "
                "refusing every deletion")
    return _process_busy_reason(wt, cache=cache)


# Directory names that are ALWAYS regenerable build output.
ALWAYS = {"node_modules", ".venv", ".next", ".turbo"}
# Reclaimed only when a sibling file proves it is build output, not source.
CONDITIONAL = {"target": "Cargo.toml"}

# Session machinery, never source — excluded from the idle reading for the same
# reason the root dir is (defect [1]): a file the TOOLING writes must not look
# like a human edit. A session lock is touched by every session that opens the
# worktree, so counting it would make a worktree read "active" for a full idle
# window after the last session ended — and, since the lock is checked AFTER the
# idle threshold, the honest "preserved: live session lock" report would never
# print. Liveness is decided by has_live_session_lock(), on the lock's own clock.
SKIP_SOURCE_NAMES = {".session-lock", ".session-lock.json"}

# Free space -> idle threshold (days). Each rung's trigger is
# max(absolute_gb, pct_of_volume), mirroring the proportional floor in
# hooks/worktree-footprint-signal.py: a flat number does not scale with the disk.
# 150 GB free is comfortable on a 500 GB laptop and a five-alarm fire on a 4 TB
# workstation, so the rungs scale with the volume and the absolute values act as
# floors for small disks. Ascending caps, first match wins; above the last rung
# the tool is a no-op, so a healthy disk keeps every build cache warm. The 0.0
# rung exists so the floor is defended even when every worktree is freshly built.
#   (pct_of_volume, absolute_gb, idle_days)
PRESSURE_LADDER = (
    (0.02, 20.0, 0.0),
    (0.04, 40.0, 1.0),
    (0.09, 80.0, 3.0),
    (0.16, 150.0, 7.0),
)

# Walk guard: a source tree is small once artifact dirs are skipped, but a
# pathological checkout must not stall the whole fleet run. A walk that hits this
# bound has NOT seen the whole source, so its idle reading is a partial sample —
# see idle_days(), which reports truncation rather than trusting it.
MAX_SOURCE_ENTRIES = 40_000


def ladder_idle_days(free_gb: float, total_gb: float | None = None):
    """Idle threshold for the current free space, or None when there is no pressure.

    total_gb=None keeps the pure absolute ladder (the small-disk floor), so the
    arithmetic is testable without faking a volume.
    """
    for pct, absolute, idle in PRESSURE_LADDER:
        cap = absolute if total_gb is None else max(absolute, total_gb * pct)
        if free_gb < cap:
            return idle
    return None


def ladder_caps(total_gb: float | None = None) -> list[float]:
    """The effective trigger (GB free) of each rung, for reporting and controls."""
    return [absolute if total_gb is None else max(absolute, total_gb * pct)
            for pct, absolute, _ in PRESSURE_LADDER]


def idle_days(wt: Path, now: float) -> tuple[float, str | None]:
    """(days since the worktree's SOURCE was last touched, unmeasurable_reason).

    A non-None reason means the reading cannot be trusted and the caller must
    preserve. It is a REASON rather than a flag so the report can say which.

    Newest mtime over source entries, skipping .git and every artifact dir. The
    worktree ROOT is deliberately excluded: its mtime bumps whenever an entry is
    created or removed inside it, so `cargo build` writing target/ would mark the
    worktree "active" and protect the very artifact this tool exists to reclaim.

    The truncation flag is load-bearing. A walk that stops at MAX_SOURCE_ENTRIES
    has seen only a PREFIX of the source, and the file someone edited an hour ago
    may sit in the unvisited remainder — so a partial walk can report a worktree
    as idle precisely when it is in active use. The caller preserves on
    truncation and says so; this tool deletes, so an unknown reads as "in use".

    The same applies to a walk that reads NOTHING. Every lstat here is guarded,
    because one unreadable entry must not abort a fleet run — but if EVERY entry
    fails (a permissions problem, a dataless cloud placeholder, a half-mounted
    volume) the newest-mtime is still 0.0, which reads as infinitely idle and
    would delete the artifacts of a worktree we could not measure at all. So
    "measured nothing" is reported as unmeasurable, exactly like truncation, and
    never as maximally stale.
    """
    best = 0.0
    seen = 0
    truncated: str | None = None
    for root, dirs, files in os.walk(wt, topdown=True, onerror=lambda e: None):
        for d in list(dirs):
            if d == ".git" or d in ALWAYS or (
                d in CONDITIONAL and (Path(root) / CONDITIONAL[d]).exists()
            ):
                dirs.remove(d)
        # Sub-directories still carry signal (a new source dir is real activity);
        # only the root is excluded, and os.walk yields it first.
        entries = files if Path(root) == wt else files + dirs
        for name in entries:
            if name in SKIP_SOURCE_NAMES:
                continue
            try:
                best = max(best, os.lstat(os.path.join(root, name)).st_mtime)
            except OSError:
                pass
            seen += 1
        if seen > MAX_SOURCE_ENTRIES:
            truncated = (f"source walk exceeded {MAX_SOURCE_ENTRIES} entries, "
                         f"so the idle reading is only a prefix of the source")
            break
    if not best:
        # Nothing readable: unmeasurable, not "infinitely idle".
        return 0.0, ("no source entry could be read (permissions, a dataless "
                     "cloud placeholder, or a worktree with no source at all)")
    return (now - best) / 86400, truncated


def dir_size_mb(p: Path) -> int:
    # A symlinked artifact costs nothing here and its target may live outside the
    # worktree — never follow it, never bill it.
    if is_link(p):
        return 0
    total = 0
    for root, _dirs, files in os.walk(p, onerror=lambda e: None):
        for f in files:
            try:
                total += os.lstat(os.path.join(root, f)).st_size
            except OSError:
                pass
    return total // (1024 * 1024)


def is_link(p: Path) -> bool:
    """Symlink, or a Windows junction (which is not a symlink to os.path)."""
    try:
        if p.is_symlink():
            return True
    except OSError:
        return False
    isjunction = getattr(os.path, "isjunction", None)
    if isjunction is not None:
        try:
            return bool(isjunction(p))
        except OSError:
            return False
    return False


# Liveness is decided by _lib.has_live_session_lock, never a copy living here.
# This file shipped with its own, which probed `<wt>/.session-lock` — a filename
# that exists nowhere on a real machine — so the guard was dead in production
# while reading, correctly, as "no session here". At the 0-day pressure rung
# every worktree passes the idle gate, which makes this the ONLY protection
# between an actively-compiling worktree and losing its `target/`.


def find_artifacts(wt: Path):
    """Yield reclaimable artifact dirs inside one worktree, never descending into them."""
    for root, dirs, _files in os.walk(wt, topdown=True, onerror=lambda e: None):
        for d in list(dirs):
            full = Path(root) / d
            if d == ".git":
                dirs.remove(d)
            elif d in ALWAYS:
                dirs.remove(d)          # do not descend into what we delete
                yield full
            elif d in CONDITIONAL and (Path(root) / CONDITIONAL[d]).exists():
                dirs.remove(d)
                yield full


def plan(dev_root: Path, min_idle: float, now: float) -> tuple[list, list]:
    """(reclaimable artifacts, skipped-worktree notes). Never silently drops one."""
    out: list = []
    skipped: list = []
    # One process-table reading for the whole planning pass. The apply loop takes
    # its OWN, because sizing every candidate can take minutes and a build can
    # start in that window.
    probe_cache: dict = {}
    if not dev_root.is_dir():
        return out, skipped
    try:
        entries = sorted(os.listdir(dev_root))
    except OSError as e:
        skipped.append(f"{dev_root}: unreadable ({e})")
        return out, skipped
    for entry in entries:
        wt = dev_root / entry
        if not wt.is_dir() or is_link(wt):
            continue
        age, unmeasurable = idle_days(wt, now)
        if unmeasurable:
            # Fail LOUD, not silent: an unmeasurable worktree is reported with
            # its reason, so a client can see why their biggest checkout is
            # never reclaimed instead of assuming the pass covered it.
            skipped.append(f"{entry}: {unmeasurable} — preserved")
            continue
        if age < min_idle:
            continue
        if has_live_session_lock(wt, now):
            skipped.append(f"{entry}: live session lock, preserved")
            continue
        # The session lock is a PROXY and fails OPEN: it depends on a writer that
        # stops emitting during one long call, and its own probe falls through to
        # lock files when it cannot measure. A running compiler is direct
        # evidence and fails CLOSED.
        busy = worktree_busy(wt, probe_cache)
        if busy:
            skipped.append(f"{entry}: {busy}, preserved")
            continue
        for art in find_artifacts(wt):
            out.append({"worktree": str(wt), "path": str(art),
                        "idle_days": round(age, 1)})
    return out, skipped


def _force_remove(func, path, _exc):
    """Windows refuses to unlink a read-only file, and cargo/npm leave plenty."""
    try:
        os.chmod(path, stat.S_IWRITE)
    except OSError:
        raise
    func(path)


def remove_artifact(p: Path) -> None:
    # rmtree refuses a symlink; unlinking drops the pointer without ever
    # following it out of the worktree.
    if is_link(p):
        try:
            p.unlink()
        except (OSError, IsADirectoryError, PermissionError):
            os.rmdir(p)          # Windows junction
        return
    if sys.version_info >= (3, 12):
        shutil.rmtree(p, onexc=_force_remove)
    else:
        shutil.rmtree(p, onerror=_force_remove)


def disk(path: Path):
    """Usage of the volume the dev root actually lives on, not the home volume —
    a client's code may sit on a second drive, and defending the wrong volume's
    floor is the same as defending none."""
    for p in (path, Path.home()):
        try:
            return shutil.disk_usage(str(p))
        except OSError:
            continue
    return None


def log_dir() -> Path:
    override = os.environ.get("DEV_BUILD_RECLAIM_LOG_DIR", "").strip()
    if override:
        return Path(override).expanduser()
    return Path.home() / ".claude" / "logs" / "dev-repo-reaper"


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Reclaim regenerable build artifacts from idle worktrees.")
    ap.add_argument("--apply", action="store_true", help="actually delete (default: dry-run)")
    ap.add_argument("--min-idle-days", type=float, default=None,
                    help="pin the idle threshold; default scales with free space (PRESSURE_LADDER)")
    ap.add_argument("--min-free-gb", type=float, default=None,
                    help="no-op unless free space is below this (for cron: only act under pressure)")
    ap.add_argument("--dev-root", help="override the dev root for this run")
    ap.add_argument("--json", action="store_true", help="machine-readable plan")
    a = ap.parse_args()

    dev_root = Path(a.dev_root).expanduser() if a.dev_root else resolve_dev_root()

    usage = disk(dev_root)
    if usage is None:
        msg = f"cannot stat the volume holding {dev_root} — refusing to guess"
        print(json.dumps({"error": msg}) if a.json else f"dev-build-reclaim: {msg}",
              file=sys.stderr)
        return 2
    before = usage.free / (1024 ** 3)
    total = usage.total / (1024 ** 3)

    if a.min_free_gb is not None and before >= a.min_free_gb:
        msg = f"free {before:.0f} GB >= threshold {a.min_free_gb:.0f} GB — no-op"
        print(json.dumps({"skipped": msg}) if a.json else msg)
        return 0

    if a.min_idle_days is not None:
        min_idle, tier = a.min_idle_days, "pinned by --min-idle-days"
    else:
        laddered = ladder_idle_days(before, total)
        if laddered is None:
            top = ladder_caps(total)[-1]
            msg = (f"free {before:.0f} GB >= {top:.0f} GB "
                   f"({total:.0f} GB volume) — no pressure, no-op")
            print(json.dumps({"skipped": msg}) if a.json else msg)
            return 0
        min_idle = laddered
        tier = f"pressure ladder @ {before:.0f} GB free of {total:.0f} GB"

    now = time.time()
    items, skipped = plan(dev_root, min_idle, now)
    for it in items:
        it["size_mb"] = dir_size_mb(Path(it["path"]))
    # Largest first: a pressure-triggered run must buy back the most space in its
    # first seconds, not its last.
    items.sort(key=lambda i: -i["size_mb"])

    total_mb = sum(i["size_mb"] for i in items)
    worktrees = {i["worktree"] for i in items}

    deleted, failed = 0, []
    if a.apply and items:
        ldir = log_dir()
        ldir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        manifest = ldir / f"build-reclaim-{stamp}.jsonl"
        # Builtin open with an explicit positional mode, not Path.open("a"): the
        # cloud-safe-walker gate proves write-only from `open(path, MODE)` and
        # cannot see the mode when it is Path.open's first argument, so the
        # append would read to it as a recursive content read.
        # A FRESH probe, not plan()'s. Sizing every candidate above walks hundreds
        # of gigabytes and can take minutes; on a shared machine a liveness
        # reading has a shelf life measured in minutes, so it is re-taken here,
        # immediately before the first deletion.
        apply_probe_cache: dict = {}
        with open(manifest, "a", encoding="utf-8") as mf:
            for it in items:
                busy = worktree_busy(Path(it["worktree"]), apply_probe_cache)
                if busy:
                    skipped.append(f"{os.path.basename(it['worktree'])}: "
                                   f"{busy} at apply time, preserved")
                    continue
                try:
                    remove_artifact(Path(it["path"]))
                    deleted += 1
                    mf.write(json.dumps({**it, "ts": datetime.now(timezone.utc).isoformat()}) + "\n")
                except OSError as e:
                    failed.append(f"{it['path']}: {e}")

    after = (disk(dev_root) or usage).free / (1024 ** 3)
    result = {
        "dirs": len(items), "worktrees": len(worktrees),
        "size_gb": round(total_mb / 1024, 1), "applied": a.apply,
        "deleted": deleted, "failed": failed, "skipped": skipped,
        "dev_root": str(dev_root),
        "free_gb_before": round(before, 1), "free_gb_after": round(after, 1),
        "volume_gb": round(total, 1),
        "min_idle_days": min_idle, "threshold_source": tier,
    }

    if a.json:
        print(json.dumps(result, indent=1))
        return 0

    per_wt: dict[str, int] = {}
    for i in items:
        per_wt[i["worktree"]] = per_wt.get(i["worktree"], 0) + i["size_mb"]
    for wt, mb in sorted(per_wt.items(), key=lambda kv: -kv[1])[:12]:
        print(f"  {mb/1024:6.1f} GB  {os.path.basename(wt)}")

    verb = "RECLAIMED" if a.apply else "WOULD RECLAIM"
    print(f"\n{verb}: {len(items)} dirs, {total_mb/1024:.1f} GB across "
          f"{len(worktrees)} worktree(s) (source idle >= {min_idle}d — {tier})")
    if skipped:
        print(f"  {len(skipped)} worktree(s) preserved:", *skipped[:5], sep="\n    ")
    if failed:
        print(f"  {len(failed)} failed:", *failed[:5], sep="\n    ")
    if a.apply:
        print(f"  free: {before:.0f} GB -> {after:.0f} GB")
    else:
        print("Re-run with --apply to execute.")
    return 0


if __name__ == "__main__":
    # Windows cp1252-console safety (#313): the output carries non-ASCII (the em
    # dashes and >= glyphs). An unguarded print raises UnicodeEncodeError there,
    # and a reclaim tool whose report cannot print reads as a tool that did nothing.
    for _stream in (sys.stdout, sys.stderr):
        try:
            _stream.reconfigure(encoding="utf-8")  # Python 3.7+
        except (AttributeError, ValueError):
            pass
    sys.exit(main())
